In [50]:
import torch

In [51]:
# Empty tensor (uninitialized values)
a = torch.empty(2, 3)
print("Empty tensor:\n", a)

# Tensor filled with zeros
b = torch.zeros(2, 3)
print("Zeros tensor:\n", b)

# Tensor filled with ones
c = torch.ones(2, 3)
print("Ones tensor:\n", c)

# Tensor from list
d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Tensor from list:\n", d)

# Tensor with a specific value
e = torch.full((2, 3), 7)
print("Tensor filled with 7s:\n", e)

# Identity matrix
f = torch.eye(3)
print("Identity matrix:\n", f)

Empty tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Zeros tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Tensor from list:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Tensor filled with 7s:
 tensor([[7, 7, 7],
        [7, 7, 7]])
Identity matrix:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [52]:
x = torch.tensor([10, 20, 30], dtype=torch.float32)
y = torch.tensor([1, 2, 3], dtype=torch.float32)

# Addition
print("Addition:", x + y)

# Subtraction
print("Subtraction:", x - y)

# Multiplication
print("Multiplication:", x * y)

# Division
print("Division:", x / y)

Addition: tensor([11., 22., 33.])
Subtraction: tensor([ 9., 18., 27.])
Multiplication: tensor([10., 40., 90.])
Division: tensor([10., 10., 10.])


In [53]:
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [54]:
# Create tensors with requires_grad=True to track computation
a = torch.tensor([5.0], requires_grad=True)
b = torch.tensor([6.0], requires_grad=True)

# Define a function of a and b
y = a**3 - b**2 + 3

# Perform backpropagation to compute gradients
y.backward()

# Print the gradients
print("dy/da:", a.grad)  # Should be 3 * a^2 = 3 * 25 = 75
print("dy/db:", b.grad)  # Should be -2 * b = -12

dy/da: tensor([75.])
dy/db: tensor([-12.])


In [55]:
z = a * b
print(a.grad)
z.backward()

print(a.grad)

tensor([75.])
tensor([81.])


In [56]:
# Initialize parameters with requires_grad=True
w = torch.tensor([2.0, 3.0, 9.0], requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)

x = torch.tensor([3.0, 0.0, 1.0])
y_true = torch.tensor([5.0])

for _ in range(100):
    y_pred = b + torch.sum(w * x)  # Use torch.sum
    loss = (y_pred - y_true).pow(2)
    
    loss.backward()  # No need for Variable(loss, ...)
    
    with torch.no_grad():
        w -= 0.01 * w.grad
        b -= 0.01 * b.grad
    
    w.grad.zero_()  # Reset gradients
    b.grad.zero_()

In [60]:
torch.sum(w * x)

tensor(5.0000, grad_fn=<SumBackward0>)

In [61]:
# 1. Generate synthetic data: y = 2x + 1 + noise
torch.manual_seed(0)
x = torch.linspace(0, 10, 100).view(-1, 1)  # shape [100, 1]
y = 2 * x + 1 + torch.randn(x.size()) * 1.0  # shape [100, 1]

# 2. Initialize parameters (weights and bias) with requires_grad=True
w = torch.randn(1, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# 3. Set learning rate and number of epochs
learning_rate = 0.01
epochs = 200

# 4. Training loop
for epoch in range(epochs):
    # Forward pass: compute predictions
    y_pred = x @ w + b  # matrix multiply and add bias

    # Compute mean squared error loss
    loss = ((y_pred - y) ** 2).mean()

    # Backward pass: compute gradients
    loss.backward()

    # Update parameters manually (no optimizer)
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

    # Zero gradients for next step
    w.grad.zero_()
    b.grad.zero_()

    # Print loss every 20 epochs
    if (epoch + 1) % 20 == 0:
        print(f"Epoch {epoch+1}: Loss = {loss.item():.4f}")

# 5. Print learned parameters
print(f"Learned weight: {w.item():.4f}, bias: {b.item():.4f}")

Epoch 20: Loss = 1.2121
Epoch 40: Loss = 1.1827
Epoch 60: Loss = 1.1587
Epoch 80: Loss = 1.1390
Epoch 100: Loss = 1.1228
Epoch 120: Loss = 1.1096
Epoch 140: Loss = 1.0987
Epoch 160: Loss = 1.0898
Epoch 180: Loss = 1.0826
Epoch 200: Loss = 1.0766
Learned weight: 2.0486, bias: 0.7133
