In [1]:
import torch

In [ ]:
a = torch.empty(2, 3)
print(a)

b = torch.zeros(3, 3)
print(b)

c = torch.ones(4)
print(c)

d = torch.full((2, 3), 10)
print(d)

tensor([1., 1., 1., 1.])
tensor([[10, 10, 10],
        [10, 10, 10]])


In [ ]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
torch.randn(2, 3, 4)

tensor([[[-1.3321, -0.6498,  0.4663,  0.7584],
         [ 1.7257, -0.3758, -0.6787, -1.1201],
         [-0.2862,  2.0396,  0.2389, -1.0142]],

        [[ 0.9203,  2.6145,  0.2254,  0.5829],
         [-0.6697, -1.8369, -0.2352,  1.4239],
         [ 0.1138, -0.8749,  1.0471,  1.9192]]])

In [40]:
x = torch.tensor([10, 20, 30], dtype=torch.float32)
y = torch.tensor([1, 2, 3, 5], dtype=torch.float32)

print(x)
print(y)

print(x + y)
print(x - y)
print(x * y)
print(x / y)

tensor([10., 20., 30.])
tensor([1., 2., 3., 5.])


RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0

In [53]:
# Create a 3x2 tensor with random values sampled from a standard normal distribution
x = torch.randn(3, 2, 2, 2)

print(x)

x.view(3,2,-1)


tensor([[[[-1.1177, -1.5782],
          [-0.6158,  0.9322]],

         [[ 0.9391,  0.3837],
          [ 0.3381, -0.3848]]],


        [[[-0.4934, -0.8062],
          [ 0.6122, -0.1161]],

         [[-0.9119, -1.6575],
          [-2.2442,  0.8647]]],


        [[[ 0.4187,  0.5767],
          [-0.5893, -0.7746]],

         [[ 1.7357, -1.1219],
          [ 1.8183,  1.1442]]]])


tensor([[[-1.1177, -1.5782, -0.6158,  0.9322],
         [ 0.9391,  0.3837,  0.3381, -0.3848]],

        [[-0.4934, -0.8062,  0.6122, -0.1161],
         [-0.9119, -1.6575, -2.2442,  0.8647]],

        [[ 0.4187,  0.5767, -0.5893, -0.7746],
         [ 1.7357, -1.1219,  1.8183,  1.1442]]])

In [58]:
import numpy as np

np_array = np.array([[1, 2, 3], [4, 5, 6]])

print(np_array)


a = torch.from_numpy(np_array)
print(a)

b = a.detach().cpu().numpy()
print(b)

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]])
[[1 2 3]
 [4 5 6]]
