In [57]:
from pprint import pp

import torch
import torch.nn.functional as F
from sklearn.metrics import classification_report


In [58]:
num_samples = 10
num_classes = 3

# Create random logits for demonstration
logits = torch.randn(num_samples, num_classes)
print(logits)


tensor([[-1.0658,  0.8703,  0.2756],
        [-0.1196,  0.0737, -0.9799],
        [-0.2806, -1.2762,  1.0003],
        [-0.3413,  1.1065,  0.2878],
        [ 0.5386,  1.1175, -1.9599],
        [ 0.5392, -0.6018,  0.5759],
        [-0.7716, -0.7719,  1.3992],
        [-0.3515,  0.0735,  1.8764],
        [-0.8695,  0.3263,  2.1753],
        [-0.5393, -0.5253, -1.5496]])


In [59]:
# Apply softmax to convert logits to probabilities.
probs = F.softmax(logits, dim=1)  # Shape: (batch_size, num_classes)
print(probs)

# Notice that the probabilities for each sample sum to 1.
sum_probs = probs.sum(dim=1)
print(sum_probs)

tensor([[0.0851, 0.5896, 0.3253],
        [0.3793, 0.4602, 0.1605],
        [0.2012, 0.0744, 0.7244],
        [0.1403, 0.5966, 0.2631],
        [0.3489, 0.6224, 0.0287],
        [0.4243, 0.1356, 0.4402],
        [0.0929, 0.0929, 0.8142],
        [0.0847, 0.1295, 0.7858],
        [0.0395, 0.1306, 0.8299],
        [0.4205, 0.4264, 0.1531]])
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000])


In [60]:
# Use argmax to get the predicted class index for each sample
pred_labels = torch.argmax(probs, dim=1)  # Shape: (batch_size, )
print(pred_labels)

# Create random true labels for demonstration
true_labels = torch.randint(0, num_classes, (num_samples,))
print(true_labels)  # Shape: (batch_size, )

tensor([1, 1, 2, 1, 1, 2, 2, 2, 2, 1])
tensor([2, 0, 1, 1, 0, 0, 0, 2, 2, 2])


In [61]:
# Move prediction and label tensors to CPU and convert to numpy arrays for scikit-learn compatibility
pred_labels_np = pred_labels.cpu().numpy()
true_labels_np = true_labels.cpu().numpy()

In [62]:
# Generate the classification report as a dictionary (includes precision, recall, f1, etc.)
report = classification_report(true_labels_np, pred_labels_np, output_dict=False)
print(report)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         4
           1       0.20      0.50      0.29         2
           2       0.40      0.50      0.44         4

    accuracy                           0.30        10
   macro avg       0.20      0.33      0.24        10
weighted avg       0.20      0.30      0.23        10



c:\Users\admin\Coding\ai-technique-68\codes\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\admin\Coding\ai-technique-68\codes\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\admin\Coding\ai-technique-68\codes\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier,

In [63]:
# If you want the report as a dictionary for easier access to specific metrics, set output_dict=True
report = classification_report(true_labels_np, pred_labels_np, output_dict=True)
pp(report)

{'0': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 4.0},
 '1': {'precision': 0.2,
       'recall': 0.5,
       'f1-score': 0.2857142857142857,
       'support': 2.0},
 '2': {'precision': 0.4,
       'recall': 0.5,
       'f1-score': 0.4444444444444444,
       'support': 4.0},
 'accuracy': 0.3,
 'macro avg': {'precision': 0.20000000000000004,
               'recall': 0.3333333333333333,
               'f1-score': 0.24338624338624337,
               'support': 10.0},
 'weighted avg': {'precision': 0.2,
                  'recall': 0.3,
                  'f1-score': 0.2349206349206349,
                  'support': 10.0}}


c:\Users\admin\Coding\ai-technique-68\codes\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\admin\Coding\ai-technique-68\codes\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\admin\Coding\ai-technique-68\codes\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier,

In [64]:
# To access specific metrics, you can do something like:
pp(report["accuracy"])

0.3


In [ ]:
# F1-score is often used as a single metric to summarize the performance of a classifier, especially when dealing with imbalanced datasets. 
# The "weighted avg" f1-score takes into account the support (number of true instances for each label) to compute an average that reflects the overall performance across all classes.
pp(report["weighted avg"]["f1-score"])

0.2349206349206349


In [66]:
def calc_metrices(logits: torch.Tensor, labels: torch.Tensor, isPrint=False):
    # Apply softmax to logits to obtain prediction probabilities for each class
    probs = F.softmax(logits, dim=1)  # Shape: (batch_size, num_classes)

    # Use argmax to get the predicted class index for each sample
    preds = torch.argmax(probs, dim=1)  # Shape: (batch_size)

    # Move prediction and label tensors to CPU and convert to numpy arrays for scikit-learn compatibility
    preds_np = preds.cpu().numpy()
    labels_np = labels.cpu().numpy()

    # Generate the classification report as a dictionary (includes precision, recall, f1, etc.)
    report = classification_report(labels_np, preds_np, output_dict=True)

    # Optionally print a nicely formatted classification report if isPrint is True
    if isPrint:
        print(classification_report(labels_np, preds_np, digits=3))

    # Return the report dictionary and the numpy arrays of predictions and labels
    return report, preds_np, labels_np

In [67]:
# Example usage:

batch_size = 20
num_classes = 5
logits = torch.randn(batch_size, num_classes)  # Example random logits
labels = torch.randint(0, num_classes, (batch_size,))  # Example random true labels
pp(logits)
pp(labels)

tensor([[ 1.7036e+00,  6.0275e-01, -3.5337e-04, -1.4714e+00, -1.5928e+00],
        [-7.6169e-02,  1.6439e-01, -6.4929e-01,  2.8130e-02, -1.9100e+00],
        [ 9.8720e-02, -7.2358e-01, -7.5867e-03, -1.0011e-01,  7.8823e-01],
        [-5.6801e-01,  3.9486e-02, -1.7988e+00, -2.9002e-01, -4.7808e-01],
        [-2.5474e-01, -1.3289e+00, -4.7951e-01, -4.5785e-01,  9.0578e-01],
        [-6.2581e-01, -1.5801e+00,  3.4379e-01,  8.0944e-01, -5.2362e-01],
        [-5.8035e-02, -6.8729e-01, -7.9133e-01, -9.6861e-01, -5.3833e-01],
        [ 1.4942e+00, -1.1414e+00, -8.3953e-01,  5.7997e-01, -3.8831e-01],
        [ 3.5099e-01,  1.5384e+00, -5.3817e-01,  1.3930e+00, -9.4446e-01],
        [ 1.8212e+00, -2.8073e-01, -3.8212e-01, -1.8191e+00,  1.1986e+00],
        [-3.8041e-01, -5.3390e-01,  5.1908e-01, -1.5600e+00, -3.0044e-01],
        [-6.1090e-01,  7.3739e-03,  5.0416e-01, -1.9897e+00, -2.3043e-02],
        [ 2.0218e+00, -4.9700e-01,  3.7890e-01,  1.0906e-01,  3.6636e-01],
        [-6.1116e-01, -1.

In [68]:
report, pred, labels = calc_metrices(logits, labels, isPrint=True)


              precision    recall  f1-score   support

           0      0.000     0.000     0.000       2.0
           1      0.000     0.000     0.000       4.0
           2      0.000     0.000     0.000       6.0
           3      0.000     0.000     0.000       3.0
           4      0.000     0.000     0.000       5.0

    accuracy                          0.000      20.0
   macro avg      0.000     0.000     0.000      20.0
weighted avg      0.000     0.000     0.000      20.0



In [69]:
pp(report)
pp(pred)
pp(labels)

{'0': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0},
 '1': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 4.0},
 '2': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 6.0},
 '3': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 3.0},
 '4': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0},
 'accuracy': 0.0,
 'macro avg': {'precision': 0.0,
               'recall': 0.0,
               'f1-score': 0.0,
               'support': 20.0},
 'weighted avg': {'precision': 0.0,
                  'recall': 0.0,
                  'f1-score': 0.0,
                  'support': 20.0}}
array([0, 1, 4, 1, 4, 3, 0, 0, 1, 0, 2, 2, 0, 4, 3, 2, 4, 4, 1, 3])
array([4, 2, 1, 4, 0, 4, 2, 2, 3, 1, 4, 1, 2, 2, 2, 3, 1, 3, 0, 4])
